version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: "ship_cms_db"
    ports:
      - "5222:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

    restart: always

volumes:
  db_data:
